<?php
/**
 * Writes a wp-config.php for a throw away test installation.
 *
 * The integration suite talks to the SQLite drop-in, so no database server is
 * needed: this file only defines the constants WordPress expects plus the debug
 * settings that make a failing test readable.
 *
 * Usage:
 *   php tests/integration/make-config.php /path/to/wordpress [--url=http://localhost:8888] [--force]
 *
 * @package USDTF
 */

// phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped -- CLI script.

$usdtf_wp_path = isset( $argv[1] ) ? rtrim( $argv[1], '/' ) : '';
$usdtf_url     = 'http://localhost:8888';
$usdtf_force   = false;

foreach ( array_slice( (array) $argv, 2 ) as $usdtf_argument ) {
	if ( 0 === strpos( $usdtf_argument, '--url=' ) ) {
		$usdtf_url = rtrim( substr( $usdtf_argument, 6 ), '/' );
	}

	if ( '--force' === $usdtf_argument ) {
		$usdtf_force = true;
	}
}

if ( '' === $usdtf_wp_path || ! file_exists( $usdtf_wp_path . '/wp-settings.php' ) ) {
	fwrite( STDERR, "Pass the path to a WordPress installation, for example: php tests/integration/make-config.php /tmp/wp\n" );
	exit( 1 );
}

$usdtf_config = $usdtf_wp_path . '/wp-config.php';

if ( file_exists( $usdtf_config ) && ! $usdtf_force ) {
	echo "wp-config.php already exists, keeping it (pass --force to overwrite).\n";
	exit( 0 );
}

$usdtf_log = $usdtf_wp_path . '/../debug.log';

$usdtf_contents = "<?php\n"
	. "// Generated by tests/integration/make-config.php for the integration suite.\n"
	. "// The database connection is handled by the SQLite drop-in, so the credentials are placeholders.\n"
	. "define( 'DB_NAME', 'wordpress' );\n"
	. "define( 'DB_USER', 'root' );\n"
	. "define( 'DB_PASSWORD', '' );\n"
	. "define( 'DB_HOST', 'localhost' );\n"
	. "define( 'DB_CHARSET', 'utf8' );\n"
	. "define( 'DB_COLLATE', '' );\n"
	. "define( 'AUTH_KEY', 'usdtf-test-auth' );\n"
	. "define( 'SECURE_AUTH_KEY', 'usdtf-test-secure' );\n"
	. "define( 'LOGGED_IN_KEY', 'usdtf-test-logged' );\n"
	. "define( 'NONCE_KEY', 'usdtf-test-nonce' );\n"
	. "define( 'AUTH_SALT', 'usdtf-test-salt' );\n"
	. "define( 'SECURE_AUTH_SALT', 'usdtf-test-secure-salt' );\n"
	. "define( 'LOGGED_IN_SALT', 'usdtf-test-logged-salt' );\n"
	. "define( 'NONCE_SALT', 'usdtf-test-nonce-salt' );\n"
	. "\$table_prefix = 'wp_';\n"
	. "\n"
	. "define( 'WP_DEBUG', true );\n"
	. "define( 'WP_DEBUG_LOG', '" . addslashes( $usdtf_log ) . "' );\n"
	. "define( 'WP_DEBUG_DISPLAY', false );\n"
	. "define( 'WP_HOME', '" . addslashes( $usdtf_url ) . "' );\n"
	. "define( 'WP_SITEURL', '" . addslashes( $usdtf_url ) . "' );\n"
	. "define( 'DISABLE_WP_CRON', true );\n"
	. "define( 'WP_ENVIRONMENT_TYPE', 'local' );\n"
	. "define( 'AUTOMATIC_UPDATER_DISABLED', true );\n"
	. "define( 'WP_AUTO_UPDATE_CORE', false );\n"
	. "\n"
	. "if ( ! defined( 'ABSPATH' ) ) {\n\tdefine( 'ABSPATH', __DIR__ . '/' );\n}\n"
	. "\n"
	. "require_once ABSPATH . 'wp-settings.php';\n";

if ( false === file_put_contents( $usdtf_config, $usdtf_contents ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- CLI script.
	fwrite( STDERR, "Could not write {$usdtf_config}\n" );
	exit( 1 );
}

echo "Wrote {$usdtf_config} (url {$usdtf_url}, log {$usdtf_log}).\n";
